import { Inter } from "next/font/google";
import "./globals.css";
import { DistributionProvider } from "./contexts/DistributionContext";
import SessionProvider from "./utils/SessionProvider";
import { DataProvider } from "./contexts/DataContext";
import {UpdateDataProvider} from './contexts/updateDataContext'
import 'react-toastify/dist/ReactToastify.css';
import ToastProvider from '../app/contexts/Toastcontext'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMCWIRE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
            <DataProvider>
            <UpdateDataProvider>
              <DistributionProvider>
              <ToastProvider >
                {children}
              </ToastProvider>
              {/* <ToastContainer /> */}
              </DistributionProvider>
            </UpdateDataProvider>
            </DataProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
