import { Inter } from "next/font/google";
import "./globals.css";
import { DistributionProvider } from "./contexts/DistributionContext";
import SessionProvider from "./utils/SessionProvider";
import { DataProvider } from "./contexts/DataContext";
import { UpdateDataProvider } from "./contexts/updateDataContext";
import "react-toastify/dist/ReactToastify.css";
import ToastProvider from "../app/contexts/Toastcontext";
import { UserProvider } from "./contexts/userData";
import SessionTimeout from "./components/SessionTimeout";
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMCWIRE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <script 
          dangerouslySetInnerHTML={{ 
            __html: `
              (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "pgxhnlvp0v");
            ` 
          }} 
        />
      </head> */}
      <body className={inter.className}>
        <SessionProvider>
          <UserProvider>
            <DataProvider>
              <UpdateDataProvider>
                <DistributionProvider>
                  <ToastProvider>
                    <SessionTimeout timeout={24 * 60 * 60 * 1000}>
                      {children}
                    </SessionTimeout>
                  </ToastProvider>
                </DistributionProvider>
              </UpdateDataProvider>
            </DataProvider>
          </UserProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
